# Generated by Django 2.0.5 on 2018-06-28 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transform',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('positionx', models.DecimalField(decimal_places=2, max_digits=20)),
                ('positiony', models.DecimalField(decimal_places=2, max_digits=20)),
                ('positionz', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rotation', models.DecimalField(decimal_places=2, max_digits=20)),
                ('scalex', models.DecimalField(decimal_places=2, max_digits=20)),
                ('scaley', models.DecimalField(decimal_places=2, max_digits=20)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.GameObject')),
            ],
        ),
    ]
