# Generated by Django 2.0.5 on 2018-06-28 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameobject',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Scene'),
        ),
    ]
