# Generated by Django 2.0.5 on 2018-06-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_transform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transform',
            old_name='scene',
            new_name='gameobject',
        ),
    ]
