// Generated by https://pagedraw.io/pages/9480
import React from 'react';
import './component_2.css';


function render() {
    return <div className="component_2-component_2" /> ;
};

export default function(props) {
    return render.apply({props: props});
}
