// Generated by https://pagedraw.io/pages/9927
import React from 'react';
import './component_1.css';


function render() {
    return <div className="component_1-component_1" /> ;
};

export default function(props) {
    return render.apply({props: props});
}
