// Generated by https://pagedraw.io/pages/9480
import React from 'react';
import Component_2 from './component_2';
import './component_1.css';


function render() {
    return <div className="component_1-component_1">
        <div className="component_1-0">
            <div className="component_1-0-0">
                <div className="component_1-0-0-0">
                    <div className="component_1-0-0-0-0">
                        <div className="component_1-oval-2" /> 
                        <div className="component_1-text-0">
                            <div>This is a website</div>
                            <br/>
                        </div>
                        <div className="component_1-check_box-2">
                            <input type="checkbox" className="component_1-0-0-0-0-2-0" /> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="component_1-1">
            <div className="component_1-component_2">
                <Component_2 /> 
            </div>
        </div>
        <div className="component_1-2">
            <div className="component_1-triangle-9">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 621 290" className="component_1-2-0-0">
                    <polygon points="0 290 621 0 621 290" className="component_1-2-0-0-0" /> 
                </svg>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
