// Generated by https://pagedraw.io/pages/9927
import React from 'react';
import List_item from './list_item';
import './fileexplorer.css';
import './styles.css'

function render() {
    return <div className="fileexplorer-fileexplorer-6">
        <div className="fileexplorer-0">
            <div className="fileexplorer-rectangle_19">
                <div className="fileexplorer-0-0-0">
                    <div className="fileexplorer-rectangle_3">
                        <div className="fileexplorer-0-0-0-0-0">
                            <div className="fileexplorer-rectangle_4-9">
                                <div className="fileexplorer-0-0-0-0-0-0-0">
                                    <div className="fileexplorer-0-0-0-0-0-0-0-0">
                                        <div className="fileexplorer-0-0-0-0-0-0-0-0-0">
                                            <div className="fileexplorer-rectangle_4" /> 
                                        </div>
                                    </div>
                                    <div className="fileexplorer-0-0-0-0-0-0-0-1">
                                        <div className="fileexplorer-0-0-0-0-0-0-0-1-0">
                                            <div className="fileexplorer-gameobjectlist-6">
                                                File Explorer
                                            </div>
                                        </div>
                                    </div>
                                    <div className="fileexplorer-0-0-0-0-0-0-0-2">
                                        <div className="fileexplorer-0-0-0-0-0-0-0-2-0">
                                            <div className="fileexplorer-rectangle_4-7" /> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="fileexplorer-0-0-1">
                    <div className="fileexplorer-rectangle-5">
                        <div className="fileexplorer-0-0-1-0-0">
                            <div className="fileexplorer-rectangle_2">
                                <div className="fileexplorer-0-0-1-0-0-0-0">
                                    <div className="fileexplorer-rectangle_1" /> 
                                    <div className="fileexplorer-0-0-1-0-0-0-0-1">
                                        <div className="fileexplorer-0-0-1-0-0-0-0-1-0">
                                            <div className="fileexplorer-text-0">
                                                <div className="dropdown">
                                                                                                    <div className="gameobjectlist-text-6" id="dropdownMenuButton" data-toggle="dropdown"
                                                                                                            aria-haspopup="true" aria-expanded="false">
                                                                                                        Create
                                                                                                    </div>
                                                                                                    <div className="dropdown-menu my-dropdown" aria-labelledby="dropdownMenuButton">
                                                                                                        <a className="dropdown-item" href="#">Action</a>
                                                                                                        <a className="dropdown-item" href="#">Another action</a>
                                                                                                        <a className="dropdown-item" href="#">Something else here</a>
                                                                                                    </div>
                                                                                            </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="fileexplorer-0-0-1-0-0-0-0-2">
                                        <div className="fileexplorer-0-0-1-0-0-0-0-2-0">
                                            <div className="fileexplorer-triangle-4">
                                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 4 4" className="fileexplorer-0-0-1-0-0-0-0-2-0-0-0">
                                                    <polygon points="0 4 4 0 4 4" className="fileexplorer-0-0-1-0-0-0-0-2-0-0-0-0" /> 
                                                </svg>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="fileexplorer-rectangle_12" /> 
                                </div>
                            </div>
                            <div className="fileexplorer-0-0-1-0-0-1">
                                <div className="fileexplorer-0-0-1-0-0-1-0">
                                    <div className="fileexplorer-rectangle_2-3">
                                        <div className="fileexplorer-0-0-1-0-0-1-0-0-0">
                                            <div className="fileexplorer-text-9">Search...</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="fileexplorer-0-0-2">
                    <div className="fileexplorer-rectangle-58" /> 
                </div>
            </div>
        </div>
        <div className="fileexplorer-1">
            <div className="fileexplorer-rectangle-0" /> 
        </div>
        <div className="fileexplorer-2">
            <div className="fileexplorer-list_item_instance-6">
                <List_item name={""} /> 
            </div>
        </div>
        <div className="fileexplorer-3">
            <div className="fileexplorer-list_item_instance-8">
                <List_item name={""} /> 
            </div>
        </div>
        <div className="fileexplorer-4">
            <div className="fileexplorer-list_item_instance-0">
                <List_item name={""} /> 
            </div>
        </div>
        <div className="fileexplorer-5">
            <div className="fileexplorer-list_item_instance-2">
                <List_item name={""} /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
