// Generated by https://pagedraw.io/pages/9927
import React from 'react';
import './front.css';


function render() {
    return <div className="front-front-9">
        <div className="front-0">
            <div className="front-0-0" /> 
            <div className="front-header_img-1">
                <div className="front-0-1-0">
                    <div className="front-path-1" style={{"background": ("linear-gradient("+"(180)"+"deg, "+(this.props.color)+", "+(this.props.color2)+")")}}>
                        <div className="front-0-1-0-0-0">
                            <div className="front-path-9">
                                <div className="front-0-1-0-0-0-0-0">
                                    <div className="front-rectangle_8" /> 
                                    <div className="front-0-1-0-0-0-0-0-1" /> 
                                    <div className="front-0-1-0-0-0-0-0-2">
                                        <div className="front-0-1-0-0-0-0-0-2-0">
                                            <div className="front-rectangle_13">
                                                <div className="front-0-1-0-0-0-0-0-2-0-0-0" /> 
                                                <div className="front-0-1-0-0-0-0-0-2-0-0-1">
                                                    <div className="front-0-1-0-0-0-0-0-2-0-0-1-0" /> 
                                                    <div className="front-rectangle_1">
                                                        <div className="front-0-1-0-0-0-0-0-2-0-0-1-1-0">
                                                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1847039577646615-1525289018545-7FD531E2-CBD7-4211-B4A0-CF04A0EF544C.png" className="front-logo_icon-1" /> 
                                                            <div className="front-0-1-0-0-0-0-0-2-0-0-1-1-0-1">
                                                                <div className="front-0-1-0-0-0-0-0-2-0-0-1-1-0-1-0">
                                                                    <div className="front-spaceplatforms-9">PyginWeb</div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div className="front-0-1-0-0-0-0-0-2-0-0-1-2" /> 
                                                    <div className="front-rectangle_18">
                                                        <div className="front-0-1-0-0-0-0-0-2-0-0-1-3-0">
                                                            <div className="front-home3">Home</div>
                                                            <a href="/home/" className="front-0-1-0-0-0-0-0-2-0-0-1-3-0-1">
                                                                <div className="front-home_1">Start Exploring</div>
                                                            </a>
                                                            <div className="front-home_2">History</div>
                                                        </div>
                                                    </div>
                                                    <div className="front-0-1-0-0-0-0-0-2-0-0-1-4" /> 
                                                </div>
                                                <div className="front-0-1-0-0-0-0-0-2-0-0-2" /> 
                                            </div>
                                        </div>
                                        <div className="front-0-1-0-0-0-0-0-2-1">
                                            <div className="front-rectangle_16">
                                                <div className="front-0-1-0-0-0-0-0-2-1-0-0" /> 
                                                <div className="front-0-1-0-0-0-0-0-2-1-0-1">
                                                    <div className="front-0-1-0-0-0-0-0-2-1-0-1-0" /> 
                                                    <div className="front-pe-6">PYGINWEB</div>
                                                    <div className="front-0-1-0-0-0-0-0-2-1-0-1-2" /> 
                                                </div>
                                                <div className="front-0-1-0-0-0-0-0-2-1-0-2" /> 
                                            </div>
                                        </div>
                                        <div className="front-0-1-0-0-0-0-0-2-2">
                                            <div className="front-rectangle_15">
                                                <div className="front-0-1-0-0-0-0-0-2-2-0-0" /> 
                                                <div className="front-0-1-0-0-0-0-0-2-2-0-1">
                                                    <div className="front-0-1-0-0-0-0-0-2-2-0-1-0" /> 
                                                    <div className="front-pe-8">
                                                        <div>PyginWeb is the ongoing discovery and exploration</div>
                                                        <div>of game development on Pygin using your browser</div>
                                                    </div>
                                                    <div className="front-0-1-0-0-0-0-0-2-2-0-1-2" /> 
                                                </div>
                                                <div className="front-0-1-0-0-0-0-0-2-2-0-2" /> 
                                            </div>
                                        </div>
                                        <div className="front-0-1-0-0-0-0-0-2-3">
                                            <div className="front-rectangle_14">
                                                <div className="front-0-1-0-0-0-0-0-2-3-0-0" /> 
                                                <div className="front-0-1-0-0-0-0-0-2-3-0-1">
                                                    <a href="/home/" className="front-0-1-0-0-0-0-0-2-3-0-1-0">
                                                        <div onClick={this.props.handleClick} className="front-start_exploring-1">
                                                            START EXPLORING
                                                        </div>
                                                    </a>
                                                </div>
                                                <div className="front-0-1-0-0-0-0-0-2-3-0-2" /> 
                                                <div className="front-0-1-0-0-0-0-0-2-3-0-3">
                                                    <div className="front-0-1-0-0-0-0-0-2-3-0-3-0" /> 
                                                    <div className="front-path-6" /> 
                                                    <div className="front-0-1-0-0-0-0-0-2-3-0-3-2" /> 
                                                </div>
                                                <div className="front-0-1-0-0-0-0-0-2-3-0-4" /> 
                                            </div>
                                        </div>
                                    </div>
                                    <div className="front-0-1-0-0-0-0-0-3" /> 
                                    <div className="front-rectangle_8-4" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="front-0-2" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
