// Generated by https://pagedraw.io/pages/9927
import React from 'react';
import './inspector.css';
import './styles.css'

function render() {
    return <div className="inspector-inspector-6">
        <div className="inspector-0">
            <div className="inspector-rectangle_3">
                <div className="inspector-0-0-0">
                    <div className="inspector-0-0-0-0" /> 
                    <div className="inspector-rectangle_2">
                        <div className="inspector-0-0-0-1-0">
                            <div className="inspector-rectangle_4">
                                <div className="inspector-0-0-0-1-0-0-0">
                                    <a href="/" className="inspector-0-0-0-1-0-0-0-0">
                                        <div className="inspector-gameobjectlist-1">Home</div>
                                    </a>
                                </div>
                            </div>
                            <div className="inspector-rectangle_4-5">
                                <div className="inspector-0-0-0-1-0-1-0">
                                    <a href="/home/" className="inspector-0-0-0-1-0-1-0-0">
                                        <div className="inspector-gameobjectlist-8">Account</div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="inspector-1">
            <div className="inspector-rectangle_22">
                <div className="inspector-1-0-0">
                    <div className="inspector-rectangle_3-2">
                        <div className="inspector-1-0-0-0-0">
                            <div className="inspector-rectangle_4-7">
                                <div className="inspector-1-0-0-0-0-0-0">
                                    <div className="inspector-1-0-0-0-0-0-0-0">
                                        <div className="inspector-1-0-0-0-0-0-0-0-0">
                                            <div className="inspector-rectangle_4-4" /> 
                                        </div>
                                    </div>
                                    <div className="inspector-1-0-0-0-0-0-0-1">
                                        <div className="inspector-1-0-0-0-0-0-0-1-0">
                                            <div className="inspector-gameobjectlist-2">Inspector</div>
                                        </div>
                                    </div>
                                    <div className="inspector-1-0-0-0-0-0-0-2">
                                        <div className="inspector-1-0-0-0-0-0-0-2-0">
                                            <div className="inspector-rectangle_4-3" /> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="inspector-1-0-1">
                    <div className="inspector-rectangle-5">
                        <div className="inspector-1-0-1-0-0">
                            <div className="inspector-rectangle_2-4">
                                <div className="inspector-1-0-1-0-0-0-0">
                                    <div className="inspector-rectangle_1" /> 
                                    <div className="inspector-1-0-1-0-0-0-0-1">
                                        <div className="inspector-1-0-1-0-0-0-0-1-0">
                                            <div className="inspector-text-9">
                                                <div className="dropdown">
                                                                                                    <div className="gameobjectlist-text-6" id="dropdownMenuButton" data-toggle="dropdown"
                                                                                                            aria-haspopup="true" aria-expanded="false">
                                                                                                        Create
                                                                                                    </div>
                                                                                                    <div className="dropdown-menu my-dropdown" aria-labelledby="dropdownMenuButton">
                                                                                                        <a className="dropdown-item" href="#">Mesh</a>
                                                                                                        <a className="dropdown-item" href="#">Collider</a>
                                                                                                        <a className="dropdown-item" href="#">Particle System</a>
                                                
                                                <a className="dropdown-item" href="#">Physics</a>
                                                                                                    </div>
                                                                                            </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="inspector-1-0-1-0-0-0-0-2">
                                        <div className="inspector-1-0-1-0-0-0-0-2-0">
                                            <div className="inspector-triangle-3">
                                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 4 4" className="inspector-1-0-1-0-0-0-0-2-0-0-0">
                                                    <polygon points="0 4 4 0 4 4" className="inspector-1-0-1-0-0-0-0-2-0-0-0-0" /> 
                                                </svg>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="inspector-rectangle_12" /> 
                                </div>
                            </div>
                            <div className="inspector-1-0-1-0-0-1">
                                <div className="inspector-1-0-1-0-0-1-0">
                                    <div className="inspector-rectangle_2-3">
                                        <div className="inspector-1-0-1-0-0-1-0-0-0">
                                            <div className="inspector-text-1">Search...</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="inspector-1-0-2">
                    <div className="inspector-rectangle-0" /> 
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
