// Generated by https://pagedraw.io/pages/9927
import React from 'react';
import Gameobjectlist from './gameobjectlist';
import Fileexplorer from './fileexplorer';
import Scene from './scene';
import Inspector from './inspector';
import './interface.css';
import Popup from 'reactjs-popup'

class Editor extends React.Component {
    constructor(props) {
        super(props);
        this.state = {open: false};
    }

    openModal = () => {
        this.setState({open: true});
    };
    closeModal = () => {
        this.setState({open: false});
    };


    render() {
        return (
            <div className="interface-interface-5">
                <Popup
                    open={this.openModal}
                    closeOnDocumentClick
                    onClose={this.closeModal}
                >
                    <div className="modal">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae magni
                        omnis delectus nemo, maxime molestiae dolorem numquam mollitia, voluptate
                        ea, accusamus excepturi deleniti ratione sapiente! Laudantium, aperiam
                        doloribus. Odit, aut.
                    </div>
                </Popup>
                <div className="interface-0">
                    <div className="interface-0-0">
                        <div className="interface-0-0-0">
                            <div className="interface-gameobjectlist_instance-5">
                                <Gameobjectlist/>
                            </div>
                        </div>
                        <div className="interface-0-0-1">
                            <div className="interface-fileexplorer_instance-3">
                                <Fileexplorer/>
                            </div>
                        </div>
                    </div>
                    <div className="interface-scene_instance-7">
                        <Scene/>
                    </div>
                    <div className="interface-inspector_instance-0">
                        <Inspector/>
                    </div>
                </div>
            </div>
        )
    }
}

export default Editor
