// Generated by https://pagedraw.io/pages/9927
import React from 'react';
import './list_item.css';
import './list_item_style.css'

function render(props) {
    return <div className="list_item-list_item-1">
        <div className="list_item-0">
            <div className="list_item-rectangle_2">
                <div className="list_item-0-0-0">
                    <div className="list_item-gameobjectlist-5">
                        {props.name}
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render(props);
}
