// Generated by https://pagedraw.io/pages/9927
import React from 'react';
import './physics.css';
import './physics-style.css'

function render() {
    return <div className="physics-physics-9">
        <div className="physics-0">
            <div className="physics-rectangle-1">
                <div className="physics-0-0-0">
                    <div className="physics-0-0-0-0">
                        <div className="physics-0-0-0-0-0">
                            <div className="physics-triangle-1">
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 4 4" className="physics-0-0-0-0-0-0-0">
                                    <polygon points="0 4 4 0 4 4" className="physics-0-0-0-0-0-0-0-0" /> 
                                </svg>
                            </div>
                        </div>
                    </div>
                    <div className="physics-text-5">Physics</div>
                </div>
            </div>
        </div>
        <div className="physics-1">
            <div className="physics-rectangle-4">
                <div className="physics-1-0-0">
                    <div className="physics-1-0-0-0">
                        <div className="physics-1-0-0-0-0">
                            <div className="physics-text-53">Mass</div>
                        </div>
                    </div>
                    <input type="text" placeholder="10" className="physics-text_input-0" /> 
                </div>
            </div>
        </div>
        <div className="physics-2">
            <div className="physics-rectangle-6">
                <div className="physics-2-0-0">
                    <div className="physics-2-0-0-0">
                        <div className="physics-2-0-0-0-0">
                            <div className="physics-text-4">Gravity</div>
                        </div>
                    </div>
                    <div className="physics-rectangle_2">
                        <div className="physics-2-0-0-1-0">
                            <input type="text" placeholder="98" className="physics-text_input-6" /> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="physics-3">
            <div className="physics-rectangle-8">
                <div className="physics-3-0-0">
                    <div className="physics-3-0-0-0">
                        <div className="physics-3-0-0-0-0">
                            <div className="physics-text-1">Velocity</div>
                        </div>
                    </div>
                    <div className="physics-rectangle_27">
                        <div className="physics-3-0-0-1-0">
                            <div className="physics-rectangle_28">
                                <div className="physics-3-0-0-1-0-0-0">
                                    <div className="physics-3-0-0-1-0-0-0-0">
                                        <div className="physics-3-0-0-1-0-0-0-0-0">
                                            <div className="physics-text-3">X</div>
                                        </div>
                                    </div>
                                    <input type="text" placeholder="0" className="physics-text_input-8" /> 
                                </div>
                            </div>
                            <div className="physics-rectangle_28-7">
                                <div className="physics-3-0-0-1-0-1-0">
                                    <div className="physics-3-0-0-1-0-1-0-0">
                                        <div className="physics-3-0-0-1-0-1-0-0-0">
                                            <div className="physics-text-42">Y</div>
                                        </div>
                                    </div>
                                    <input type="text" placeholder="0" className="physics-text_input-08" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="physics-4">
            <div className="physics-rectangle-3">
                <div className="physics-4-0-0">
                    <div className="physics-4-0-0-0">
                        <div className="physics-4-0-0-0-0">
                            <div className="physics-text-57">Acceleration</div>
                        </div>
                    </div>
                    <div className="physics-rectangle_27-6">
                        <div className="physics-4-0-0-1-0">
                            <div className="physics-rectangle_28-3">
                                <div className="physics-4-0-0-1-0-0-0">
                                    <div className="physics-4-0-0-1-0-0-0-0">
                                        <div className="physics-4-0-0-1-0-0-0-0-0">
                                            <div className="physics-text-8">X</div>
                                        </div>
                                    </div>
                                    <input type="text" placeholder="0" className="physics-text_input-2" /> 
                                </div>
                            </div>
                            <div className="physics-rectangle_28-34">
                                <div className="physics-4-0-0-1-0-1-0">
                                    <div className="physics-4-0-0-1-0-1-0-0">
                                        <div className="physics-4-0-0-1-0-1-0-0-0">
                                            <div className="physics-text-31">Y</div>
                                        </div>
                                    </div>
                                    <input type="text" placeholder="0" className="physics-text_input-5" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="physics-5">
            <div className="physics-rectangle-80">
                <div className="physics-5-0-0">
                    <div className="physics-5-0-0-0">
                        <div className="physics-5-0-0-0-0">
                            <div className="physics-text-6">Angular Velocity</div>
                        </div>
                    </div>
                    <div className="physics-rectangle_27-4">
                        <div className="physics-5-0-0-1-0">
                            <input type="text" placeholder="0" className="physics-text_input-24" /> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="physics-6">
            <div className="physics-rectangle-41">
                <div className="physics-6-0-0">
                    <div className="physics-6-0-0-0">
                        <div className="physics-6-0-0-0-0">
                            <div className="physics-text-32">Angular Acceleration</div>
                        </div>
                    </div>
                    <div className="physics-rectangle_27-3">
                        <div className="physics-6-0-0-1-0">
                            <input type="text" placeholder="0" className="physics-text_input-82" /> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="physics-7">
            <div className="physics-rectangle-2">
                <div className="physics-7-0-0">
                    <div className="physics-7-0-0-0">
                        <div className="physics-7-0-0-0-0">
                            <div className="physics-text-2">Unscaled Time</div>
                        </div>
                    </div>
                    <div className="physics-check_box-3">
                        <input type="checkbox" className="physics-7-0-0-1-0" /> 
                    </div>
                </div>
            </div>
        </div>
        <div className="physics-8">
            <div className="physics-line_2" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
