// Generated by https://pagedraw.io/pages/9927
import React from 'react';
import './popup.css';


function render() {
    return <div className="popup-popup-3">
        <div className="popup-0">
            <div className="popup-rectangle_2">
                <div className="popup-0-0-0">
                    <div className="popup-0-0-0-0" /> 
                    <div className="popup-rectangle_3">
                        <div className="popup-0-0-0-1-0">
                            <div className="popup-text_2">Projects</div>
                        </div>
                        <div className="popup-0-0-0-1-1">
                            <div className="popup-line_3" /> 
                        </div>
                    </div>
                    <div className="popup-0-0-0-2" /> 
                </div>
            </div>
        </div>
        <div className="popup-1">
            <div className="popup-1-0" /> 
            <div className="popup-rectangle_31">
                <div className="popup-1-1-0">
                    <div className="popup-rectangle_36">
                        <div className="popup-1-1-0-0-0">
                            <div className="popup-text_2-3">Projeto-2</div>
                        </div>
                    </div>
                    <div className="popup-1-1-0-1">
                        <div className="popup-1-1-0-1-0">
                            <div className="popup-rectangle_30">
                                <div className="popup-1-1-0-1-0-0-0">
                                    <div className="popup-image_5" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="popup-1-2" /> 
        </div>
        <div className="popup-2">
            <div className="popup-2-0" /> 
            <div className="popup-rectangle_31-3">
                <div className="popup-2-1-0">
                    <div className="popup-rectangle_36-2">
                        <div className="popup-2-1-0-0-0">
                            <div className="popup-text_2-38">Projeto-2</div>
                        </div>
                    </div>
                    <div className="popup-2-1-0-1">
                        <div className="popup-2-1-0-1-0">
                            <div className="popup-rectangle_30-3">
                                <div className="popup-2-1-0-1-0-0-0">
                                    <div className="popup-image_5-3" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="popup-2-2" /> 
        </div>
        <div className="popup-3">
            <div className="popup-3-0" /> 
            <div className="popup-rectangle_31-7">
                <div className="popup-3-1-0">
                    <div className="popup-rectangle_36-3">
                        <div className="popup-3-1-0-0-0">
                            <div className="popup-text_2-9">Projeto-2</div>
                        </div>
                    </div>
                    <div className="popup-3-1-0-1">
                        <div className="popup-3-1-0-1-0">
                            <div className="popup-rectangle_30-7">
                                <div className="popup-3-1-0-1-0-0-0">
                                    <div className="popup-image_5-1" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="popup-3-2" /> 
        </div>
        <div className="popup-4">
            <div className="popup-rectangle_33">
                <div className="popup-4-0-0">
                    <div className="popup-4-0-0-0" /> 
                    <div className="popup-rectangle_34">
                        <div className="popup-4-0-0-1-0">
                            <input type="text" placeholder="New project's name" className="popup-text_input_4" /> 
                            <div className="popup-4-0-0-1-0-1">
                                <div className="popup-4-0-0-1-0-1-0">
                                    <div className="popup-rectangle_32">
                                        <div className="popup-4-0-0-1-0-1-0-0-0">
                                            <div className="popup-text_2-1">Create</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="popup-4-0-0-2" /> 
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
