// Generated by https://pagedraw.io/pages/9927
import React from 'react';
import './pythoneng.css';


function render() {
    return <div className="pythoneng-pythoneng-1">
        <div className="pythoneng-0">
            <div className="pythoneng-header_img-1">
                <div className="pythoneng-0-0-0">
                    <div className="pythoneng-path-10" style={{"background": ("linear-gradient("+"(180)"+"deg, "+(this.props.color)+", "+(this.props.color2)+")")}}>
                        <div className="pythoneng-0-0-0-0-0">
                            <div className="pythoneng-path-9">
                                <div className="pythoneng-0-0-0-0-0-0-0">
                                    <div className="pythoneng-rectangle_8">
                                        <div className="pythoneng-0-0-0-0-0-0-0-0-0">
                                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1847039577646615-1525289018545-7FD531E2-CBD7-4211-B4A0-CF04A0EF544C.png" className="pythoneng-logo_icon-1" /> 
                                            <div className="pythoneng-0-0-0-0-0-0-0-0-0-1">
                                                <div className="pythoneng-0-0-0-0-0-0-0-0-0-1-0">
                                                    <div className="pythoneng-spaceplatforms-9">
                                                        PythonEngine
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="pythoneng-0-0-0-0-0-0-0-1">
                                        <div className="pythoneng-0-0-0-0-0-0-0-1-0">
                                            <div className="pythoneng-0-0-0-0-0-0-0-1-0-0">
                                                <div className="pythoneng-0-0-0-0-0-0-0-1-0-0-0">
                                                    <div className="pythoneng-home3">Home</div>
                                                </div>
                                            </div>
                                            <div className="pythoneng-0-0-0-0-0-0-0-1-0-1">
                                                <div className="pythoneng-0-0-0-0-0-0-0-1-0-1-0">
                                                    <a href="https://github.com/CarlosMatheus/Engine" className="pythoneng-0-0-0-0-0-0-0-1-0-1-0-0">
                                                        <div className="pythoneng-home_1">Start Exploring</div>
                                                    </a>
                                                </div>
                                            </div>
                                            <div className="pythoneng-0-0-0-0-0-0-0-1-0-2">
                                                <div className="pythoneng-0-0-0-0-0-0-0-1-0-2-0">
                                                    <div className="pythoneng-home_2">History</div>
                                                </div>
                                            </div>
                                            <div className="pythoneng-0-0-0-0-0-0-0-1-0-3">
                                                <div className="pythoneng-0-0-0-0-0-0-0-1-0-3-0">
                                                    <div className="pythoneng-home_0">Game Exemples</div>
                                                </div>
                                            </div>
                                        </div>
                                        <div className="pythoneng-0-0-0-0-0-0-0-1-1">
                                            <div className="pythoneng-path-1" /> 
                                        </div>
                                        <div className="pythoneng-0-0-0-0-0-0-0-1-2">
                                            <div className="pythoneng-pe-6">PYTHON ENGINE</div>
                                        </div>
                                        <div className="pythoneng-0-0-0-0-0-0-0-1-3">
                                            <div className="pythoneng-pe-8">
                                                <div>Python Engine is the ongoing discovery and exploration</div>
                                                <div>of game development on Python using your browser</div>
                                            </div>
                                        </div>
                                        <div className="pythoneng-0-0-0-0-0-0-0-1-4">
                                            <a href="https://github.com/CarlosMatheus/Engine" className="pythoneng-0-0-0-0-0-0-0-1-4-0">
                                                <div onClick={this.props.handleClick} className="pythoneng-start_exploring-1">
                                                    START EXPLORING
                                                </div>
                                            </a>
                                        </div>
                                        <div className="pythoneng-0-0-0-0-0-0-0-1-5">
                                            <div className="pythoneng-path-6" /> 
                                        </div>
                                    </div>
                                    <div className="pythoneng-rectangle_8-4">
                                        <div className="pythoneng-0-0-0-0-0-0-0-2-0">
                                            <div className="pythoneng-path-4">
                                                <div className="pythoneng-0-0-0-0-0-0-0-2-0-0-0">
                                                    <div className="pythoneng-explore_pe-9">Explore PE</div>
                                                    <div className="pythoneng-0-0-0-0-0-0-0-2-0-0-0-1">
                                                        <div className="pythoneng-0-0-0-0-0-0-0-2-0-0-0-1-0">
                                                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2365337134570766-1525289018547-4CDD7854-CB79-4FB9-9A28-B46CF82318C4.png" className="pythoneng-shape-2" /> 
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="pythoneng-1">
            <div className="pythoneng-rectangle_5">
                <div className="pythoneng-1-0-0">
                    <div className="pythoneng-1-0-0-0">
                        <div className="pythoneng-1-0-0-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2686343460527720-1525289016612-78736A08-97BD-43B3-B087-811AEEFAE75D.png" className="pythoneng-line-9" /> 
                        </div>
                    </div>
                    <div className="pythoneng-1-0-0-1">
                        <div className="pythoneng-1-0-0-1-0">
                            <div className="pythoneng-june_2">FEB 2018</div>
                        </div>
                        <div className="pythoneng-1-0-0-1-1">
                            <div className="pythoneng-first_attempts_to_la-9">
                                Started the development of PE
                            </div>
                        </div>
                    </div>
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1590680948402426-1525289016441-B62358DA-F898-4463-BC2F-DD55BC1DC48B.png" className="pythoneng-line-93" /> 
                    <div className="pythoneng-1-0-0-3">
                        <div className="pythoneng-1-0-0-3-0">
                            <div className="pythoneng-february_2">MAY 2018</div>
                        </div>
                        <div className="pythoneng-1-0-0-3-1">
                            <div className="pythoneng-humans_have_decited_-7">
                                <div>Started the development of PE online</div>
                                <div>	</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="pythoneng-1-0-1">
                    <div className="pythoneng-path_1">
                        <div className="pythoneng-1-0-1-0-0">
                            <div className="pythoneng-1-0-1-0-0-0">
                                <div className="pythoneng-1-0-1-0-0-0-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2686343460527720-1525289016612-78736A08-97BD-43B3-B087-811AEEFAE75D.png" className="pythoneng-line-97" /> 
                                </div>
                                <div className="pythoneng-1-0-1-0-0-0-1">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1042056847051160-1525289016609-3F51BC58-7AA2-40E8-BFF5-89788E240D1A.png" className="pythoneng-triangle_1" /> 
                                </div>
                            </div>
                            <div className="pythoneng-1-0-1-0-0-1">
                                <div className="pythoneng-1-0-1-0-0-1-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/9304871920091418-1525289016614-4794AD92-C9CC-4B52-9DD7-614A3F5AFE57.png" className="pythoneng-triangle_1-9" /> 
                                </div>
                            </div>
                            <div className="pythoneng-1-0-1-0-0-2">
                                <div className="pythoneng-1-0-1-0-0-2-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/7196630057289239-1525289016628-EC551194-3404-40CB-9CF4-E1C13E7F343A.png" className="pythoneng-triangle_1_" /> 
                                </div>
                            </div>
                            <div className="pythoneng-1-0-1-0-0-3">
                                <div className="pythoneng-1-0-1-0-0-3-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1210754059341642-1525289016630-22E68DB3-3D8A-43CC-A5C8-0ABAF0E4A089.png" className="pythoneng-triangle_1_c" /> 
                                </div>
                                <div className="pythoneng-1-0-1-0-0-3-1">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/6343518933284316-1525289016634-5BA841BA-A113-44E6-BEA7-55B0954106D5.png" className="pythoneng-line-8" /> 
                                </div>
                            </div>
                            <div className="pythoneng-1-0-1-0-0-4">
                                <div className="pythoneng-1-0-1-0-0-4-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1601348527991068-1525289016632-652F8A5E-2487-4A80-B6EC-63411E7D7A0B.png" className="pythoneng-triangle_1-1" /> 
                                </div>
                            </div>
                            <div className="pythoneng-1-0-1-0-0-5">
                                <div className="pythoneng-1-0-1-0-0-5-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/8084586819123766-1525289016542-B144E04B-0F4E-4F30-9FFB-C50375079020.png" className="pythoneng-triangle_1_co" /> 
                                </div>
                            </div>
                            <div className="pythoneng-1-0-1-0-0-6">
                                <div className="pythoneng-1-0-1-0-0-6-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1676420804884469-1525289016545-1DA20BCF-9DCC-4456-9356-82FE3CCF1C67.png" className="pythoneng-triangle_1-16" /> 
                                </div>
                                <div className="pythoneng-1-0-1-0-0-6-1">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/6517558926925592-1525289016547-4BA5D00B-CFBD-4505-AACC-4E25EC5DDEB5.png" className="pythoneng-line-6" /> 
                                </div>
                            </div>
                            <div className="pythoneng-1-0-1-0-0-7">
                                <div className="pythoneng-1-0-1-0-0-7-0">
                                    <div className="pythoneng-august_2">APRIL 2018</div>
                                </div>
                                <div className="pythoneng-1-0-1-0-0-7-1">
                                    <div className="pythoneng-aliens_have_conquere-5">
                                        Launched the game Balance made with PE
                                    </div>
                                </div>
                            </div>
                            <div className="pythoneng-1-0-1-0-0-8">
                                <div className="pythoneng-1-0-1-0-0-8-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1590680948402426-1525289016441-B62358DA-F898-4463-BC2F-DD55BC1DC48B.png" className="pythoneng-line-69" /> 
                                </div>
                                <div className="pythoneng-1-0-1-0-0-8-1">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/7351117656817238-1525289016438-80FDF13C-3D9D-43C4-ADBA-545946FDAA07.png" className="pythoneng-triangle_1-7" /> 
                                </div>
                            </div>
                            <div className="pythoneng-1-0-1-0-0-9">
                                <div className="pythoneng-1-0-1-0-0-9-0">
                                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/2940819452121755-1525289016443-8C7C300E-2CA2-4025-A5E1-EF8E3C3CCA6E.png" className="pythoneng-triangle_1_cop" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="pythoneng-1-0-2">
                    <div className="pythoneng-1-0-2-0">
                        <div className="pythoneng-1-0-2-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/6343518933284316-1525289016634-5BA841BA-A113-44E6-BEA7-55B0954106D5.png" className="pythoneng-line-1" /> 
                        </div>
                    </div>
                    <div className="pythoneng-1-0-2-1">
                        <div className="pythoneng-1-0-2-1-0">
                            <div className="pythoneng-january_2">JANUARY 2100</div>
                        </div>
                        <div className="pythoneng-1-0-2-1-1">
                            <div className="pythoneng-first_signs_of_extra-1">
                                Started the development of Balance
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="pythoneng-2">
            <div className="pythoneng-rectangle_6">
                <div className="pythoneng-2-0-0">
                    <div className="pythoneng-rectangle_7">
                        <div className="pythoneng-2-0-0-0-0">
                            <div className="pythoneng-you_should_take_a_qu-8">
                                <div>You should take a quick look</div>
                                <div>at our game exemples</div>
                            </div>
                        </div>
                        <div className="pythoneng-2-0-0-0-1">
                            <div className="pythoneng-we_want_to_show_you_-5">
                                <div>We want to show you how the process works.</div>
                                <div>{"Display data for:"}</div>
                            </div>
                        </div>
                        <div className="pythoneng-2-0-0-0-2">
                            <div className="pythoneng-path-15">
                                <div className="pythoneng-2-0-0-0-2-0-0">
                                    <div className="pythoneng-october-1">Balance</div>
                                    <div className="pythoneng-2-0-0-0-2-0-0-1">
                                        <div className="pythoneng-2-0-0-0-2-0-0-1-0">
                                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1697042686113129-1525289016446-DFB420A1-2C8B-48A3-B3F2-679F4D7B6880.png" className="pythoneng-shape_copy-1" /> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="pythoneng-2-0-1">
                    <div className="pythoneng-rectangle_9">
                        <div className="pythoneng-2-0-1-0-0">
                            <div className="pythoneng-you_should_take_a_qu-2">
                                Balance
                            </div>
                        </div>
                        <div className="pythoneng-2-0-1-0-1">
                            <div className="pythoneng-we_want_to_show_you_-0">
                                <div>Arcade game inspired in Duet</div>
                                <br/>
                                <div>Challenge your friends! Get the highest score!</div>
                                <br/>
                                <div>{"Checkout the repository:"}</div>
                            </div>
                        </div>
                        <div className="pythoneng-2-0-1-0-2">
                            <a href="https://github.com/CarlosMatheus/Balance" className="pythoneng-2-0-1-0-2-0">
                                <div className="pythoneng-path-98">
                                    <div className="pythoneng-2-0-1-0-2-0-0-0">
                                        <div className="pythoneng-october-9">Balance</div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div className="pythoneng-rectangle_1">
                        <div className="pythoneng-2-0-1-1-0">
                            <div className="pythoneng-image-6">
                                <div className="pythoneng-2-0-1-1-0-0-0">
                                    <div className="pythoneng-rectangle_8-1" /> 
                                </div>
                                <div className="pythoneng-2-0-1-1-0-0-1">
                                    <div className="pythoneng-rectangle_8-2" /> 
                                </div>
                            </div>
                            <div className="pythoneng-image_2">
                                <div className="pythoneng-2-0-1-1-0-1-0">
                                    <div className="pythoneng-rectangle_8-0" /> 
                                </div>
                                <div className="pythoneng-2-0-1-1-0-1-1">
                                    <div className="pythoneng-rectangle_8-7" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="pythoneng-3">
            <div className="pythoneng-path-159">
                <div className="pythoneng-3-0-0">
                    <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1717925106415244-1525289016186-9552A2AF-5BC3-4F2B-8658-3633F7D055EC.png" className="pythoneng-line-17" /> 
                </div>
                <div className="pythoneng-3-0-1">
                    <div className="pythoneng-rectangle_11">
                        <div className="pythoneng-3-0-1-0-0">
                            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1287812802942318-1525289016189-74FE8C43-2A0A-4BAD-BBB2-E36E9DCF2757.png" className="pythoneng-logo_icon-12" /> 
                            <div className="pythoneng-3-0-1-0-0-1">
                                <div className="pythoneng-3-0-1-0-0-1-0">
                                    <div className="pythoneng-spaceplatforms-1">
                                        PythonEngine
                                    </div>
                                </div>
                            </div>
                            <div className="pythoneng-3-0-1-0-0-2">
                                <div className="pythoneng-3-0-1-0-0-2-0">
                                    <div className="pythoneng-legal_information_-1">
                                        {"Legal Information          Terms & Conditions"}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="pythoneng-4" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
