// Generated by https://pagedraw.io/pages/9927
import React from 'react';
import './rectanglemesh.css';


function render() {
    return <div className="rectanglemesh-rectanglemesh-2">
        <div className="rectanglemesh-0">
            <div className="rectanglemesh-rectangle-0">
                <div className="rectanglemesh-0-0-0">
                    <div className="rectanglemesh-0-0-0-0">
                        <div className="rectanglemesh-0-0-0-0-0">
                            <div className="rectanglemesh-triangle-3">
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 4 4" className="rectanglemesh-0-0-0-0-0-0-0">
                                    <polygon points="0 4 4 0 4 4" className="rectanglemesh-0-0-0-0-0-0-0-0" /> 
                                </svg>
                            </div>
                        </div>
                    </div>
                    <div className="rectanglemesh-text-8">Rectangle Mesh</div>
                </div>
            </div>
        </div>
        <div className="rectanglemesh-1">
            <div className="rectanglemesh-rectangle-7">
                <div className="rectanglemesh-1-0-0">
                    <div className="rectanglemesh-1-0-0-0">
                        <div className="rectanglemesh-1-0-0-0-0">
                            <div className="rectanglemesh-text-4">Dimensions</div>
                        </div>
                    </div>
                    <div className="rectanglemesh-rectangle_2">
                        <div className="rectanglemesh-1-0-0-1-0">
                            <div className="rectanglemesh-1-0-0-1-0-0">
                                <div className="rectanglemesh-1-0-0-1-0-0-0">
                                    <div className="rectanglemesh-text-87">Height</div>
                                </div>
                            </div>
                            <input type="text" placeholder="50" className="rectanglemesh-text_input_3" /> 
                            <div className="rectanglemesh-1-0-0-1-0-2">
                                <div className="rectanglemesh-1-0-0-1-0-2-0">
                                    <div className="rectanglemesh-text-80">Width</div>
                                </div>
                            </div>
                            <input type="text" placeholder="50" className="rectanglemesh-text_input-8" /> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="rectanglemesh-2">
            <div className="rectanglemesh-rectangle-05">
                <div className="rectanglemesh-2-0-0">
                    <div className="rectanglemesh-2-0-0-0">
                        <div className="rectanglemesh-2-0-0-0-0">
                            <div className="rectanglemesh-triangle-6">
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 4 4" className="rectanglemesh-2-0-0-0-0-0-0">
                                    <polygon points="0 4 4 0 4 4" className="rectanglemesh-2-0-0-0-0-0-0-0" /> 
                                </svg>
                            </div>
                        </div>
                    </div>
                    <div className="rectanglemesh-text-2">Material</div>
                    <div className="rectanglemesh-2-0-0-2" /> 
                </div>
            </div>
        </div>
        <div className="rectanglemesh-3">
            <div className="rectanglemesh-rectangle-2">
                <div className="rectanglemesh-3-0-0">
                    <div className="rectanglemesh-3-0-0-0">
                        <div className="rectanglemesh-3-0-0-0-0">
                            <div className="rectanglemesh-text-23">Color</div>
                        </div>
                    </div>
                    <div className="rectanglemesh-3-0-0-1" /> 
                    <div className="rectanglemesh-rectangle_28">
                        <div className="rectanglemesh-3-0-0-2-0">
                            <div className="rectanglemesh-3-0-0-2-0-0">
                                <div className="rectanglemesh-3-0-0-2-0-0-0">
                                    <div className="rectanglemesh-text-5">R</div>
                                </div>
                            </div>
                            <input type="text" placeholder="255" className="rectanglemesh-text_input-7" /> 
                        </div>
                    </div>
                    <div className="rectanglemesh-rectangle_28-5">
                        <div className="rectanglemesh-3-0-0-3-0">
                            <div className="rectanglemesh-3-0-0-3-0-0">
                                <div className="rectanglemesh-3-0-0-3-0-0-0">
                                    <div className="rectanglemesh-text-6">G</div>
                                </div>
                            </div>
                            <input type="text" placeholder="255" className="rectanglemesh-text_input-0" /> 
                        </div>
                    </div>
                    <div className="rectanglemesh-rectangle_28-0">
                        <div className="rectanglemesh-3-0-0-4-0">
                            <div className="rectanglemesh-3-0-0-4-0-0">
                                <div className="rectanglemesh-3-0-0-4-0-0-0">
                                    <div className="rectanglemesh-text-82">B</div>
                                </div>
                            </div>
                            <input type="text" placeholder="255" className="rectanglemesh-text_input-07" /> 
                        </div>
                    </div>
                    <div className="rectanglemesh-rectangle_28-8">
                        <div className="rectanglemesh-3-0-0-5-0">
                            <div className="rectanglemesh-3-0-0-5-0-0">
                                <div className="rectanglemesh-3-0-0-5-0-0-0">
                                    <div className="rectanglemesh-text-0">A</div>
                                </div>
                            </div>
                            <input type="text" placeholder="255" className="rectanglemesh-text_input-75" /> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="rectanglemesh-4">
            <div className="rectanglemesh-line_2" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
