// Generated by https://pagedraw.io/pages/9927
import React from 'react';
import './scene.css';


function render() {
    return <div className="scene-scene-3">
        <div className="scene-0">
            <div className="scene-rectangle_4">
                <div className="scene-0-0-0">
                    <div className="scene-gameobjectlist-5">Scene</div>
                </div>
            </div>
            <div className="scene-rectangle_3-9">
                <div className="scene-0-1-0">
                    <div className="scene-rectangle_3" /> 
                </div>
            </div>
        </div>
        <div className="scene-1">
            <div className="scene-screen_size_group-9" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
