// Generated by https://pagedraw.io/pages/9927
import React from 'react';
import './transform.css';


function render() {
    return <div className="transform-transform-9">
        <div className="transform-0">
            <div className="transform-rectangle-1">
                <div className="transform-0-0-0">
                    <div className="transform-0-0-0-0">
                        <div className="transform-0-0-0-0-0">
                            <div className="transform-triangle-7">
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 4 4" className="transform-0-0-0-0-0-0-0">
                                    <polygon points="0 4 4 0 4 4" className="transform-0-0-0-0-0-0-0-0" /> 
                                </svg>
                            </div>
                        </div>
                    </div>
                    <div className="transform-text-1">Transform</div>
                </div>
            </div>
        </div>
        <div className="transform-1">
            <div className="transform-rectangle-19">
                <div className="transform-1-0-0">
                    <div className="transform-1-0-0-0">
                        <div className="transform-1-0-0-0-0">
                            <div className="transform-text-8">Position</div>
                        </div>
                    </div>
                    <div className="transform-rectangle_27">
                        <div className="transform-1-0-0-1-0">
                            <div className="transform-rectangle_2">
                                <div className="transform-1-0-0-1-0-0-0">
                                    <div className="transform-1-0-0-1-0-0-0-0">
                                        <div className="transform-1-0-0-1-0-0-0-0-0">
                                            <div className="transform-text-3">X</div>
                                        </div>
                                    </div>
                                    <input type="text" placeholder="0" className="transform-text_input-5" /> 
                                </div>
                            </div>
                            <div className="transform-rectangle_28">
                                <div className="transform-1-0-0-1-0-1-0">
                                    <div className="transform-1-0-0-1-0-1-0-0">
                                        <div className="transform-1-0-0-1-0-1-0-0-0">
                                            <div className="transform-text-10">Y</div>
                                        </div>
                                    </div>
                                    <input type="text" placeholder="0" className="transform-text_input-4" /> 
                                </div>
                            </div>
                            <div className="transform-rectangle_28-1">
                                <div className="transform-1-0-0-1-0-2-0">
                                    <div className="transform-1-0-0-1-0-2-0-0">
                                        <div className="transform-1-0-0-1-0-2-0-0-0">
                                            <div className="transform-text-7">Z</div>
                                        </div>
                                    </div>
                                    <input type="text" placeholder="0" className="transform-text_input-0" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="transform-2">
            <div className="transform-rectangle-14">
                <div className="transform-2-0-0">
                    <div className="transform-2-0-0-0">
                        <div className="transform-2-0-0-0-0">
                            <div className="transform-text-89">Rotation</div>
                        </div>
                    </div>
                    <div className="transform-rectangle_27-9">
                        <div className="transform-2-0-0-1-0">
                            <div className="transform-rectangle_28-9">
                                <div className="transform-2-0-0-1-0-0-0">
                                    <div className="transform-2-0-0-1-0-0-0-0">
                                        <div className="transform-2-0-0-1-0-0-0-0-0">
                                            <div className="transform-text-6">X</div>
                                        </div>
                                    </div>
                                    <input type="text" placeholder="0" className="transform-text_input_2" /> 
                                </div>
                            </div>
                            <div className="transform-rectangle_28-5">
                                <div className="transform-2-0-0-1-0-1-0">
                                    <div className="transform-2-0-0-1-0-1-0-0">
                                        <div className="transform-2-0-0-1-0-1-0-0-0">
                                            <div className="transform-text-14">Y</div>
                                        </div>
                                    </div>
                                    <input type="text" placeholder="0" className="transform-text_input-1" /> 
                                </div>
                            </div>
                            <div className="transform-rectangle_28-93">
                                <div className="transform-2-0-0-1-0-2-0">
                                    <div className="transform-2-0-0-1-0-2-0-0">
                                        <div className="transform-2-0-0-1-0-2-0-0-0">
                                            <div className="transform-text-79">Z</div>
                                        </div>
                                    </div>
                                    <input type="text" placeholder="0" className="transform-text_input-9" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="transform-3">
            <div className="transform-rectangle-4">
                <div className="transform-3-0-0">
                    <div className="transform-3-0-0-0">
                        <div className="transform-3-0-0-0-0">
                            <div className="transform-text-34">Scale</div>
                        </div>
                    </div>
                    <div className="transform-rectangle_27-7">
                        <div className="transform-3-0-0-1-0">
                            <div className="transform-rectangle_28-6">
                                <div className="transform-3-0-0-1-0-0-0">
                                    <div className="transform-3-0-0-1-0-0-0-0">
                                        <div className="transform-3-0-0-1-0-0-0-0-0">
                                            <div className="transform-text-5">X</div>
                                        </div>
                                    </div>
                                    <input type="text" placeholder="0" className="transform-text_input_2-6" /> 
                                </div>
                            </div>
                            <div className="transform-rectangle_28-17">
                                <div className="transform-3-0-0-1-0-1-0">
                                    <div className="transform-3-0-0-1-0-1-0-0">
                                        <div className="transform-3-0-0-1-0-1-0-0-0">
                                            <div className="transform-text-77">Y</div>
                                        </div>
                                    </div>
                                    <input type="text" placeholder="0" className="transform-text_input-45" /> 
                                </div>
                            </div>
                            <div className="transform-rectangle_28-3">
                                <div className="transform-3-0-0-1-0-2-0">
                                    <div className="transform-3-0-0-1-0-2-0-0">
                                        <div className="transform-3-0-0-1-0-2-0-0-0">
                                            <div className="transform-text-88">Z</div>
                                        </div>
                                    </div>
                                    <input type="text" placeholder="0" className="transform-text_input-8" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="transform-4">
            <div className="transform-line_2" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
