// Generated by https://pagedraw.io/pages/9927
import React from 'react';
import './transform.css';


function render() {
    return <div className="transform-transform-9">
        <div className="transform-0">
            <div className="transform-rectangle-1">
                <div className="transform-0-0-0">
                    <div className="transform-0-0-0-0">
                        <div className="transform-0-0-0-0-0">
                            <div className="transform-triangle-7">
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 4 4" className="transform-0-0-0-0-0-0-0">
                                    <polygon points="0 4 4 0 4 4" className="transform-0-0-0-0-0-0-0-0" /> 
                                </svg>
                            </div>
                        </div>
                    </div>
                    <div className="transform-text-1">Transform</div>
                </div>
            </div>
        </div>
        <div className="transform-1">
            <div className="transform-rectangle-19">
                <div className="transform-1-0-0">
                    <div className="transform-1-0-0-0">
                        <div className="transform-1-0-0-0-0">
                            <div className="transform-text-8">Position</div>
                        </div>
                    </div>
                    <div className="transform-rectangle_28">
                        <div className="transform-1-0-0-1-0">
                            <div className="transform-rectangle_27">
                                <div className="transform-1-0-0-1-0-0-0">
                                    <div className="transform-1-0-0-1-0-0-0-0">
                                        <div className="transform-1-0-0-1-0-0-0-0-0">
                                            <div className="transform-text-3">X</div>
                                        </div>
                                    </div>
                                    <div className="transform-rectangle_2">
                                        <div className="transform-1-0-0-1-0-0-0-1-0">
                                            <div className="transform-text-4">0</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="transform-rectangle_27-1">
                                <div className="transform-1-0-0-1-0-1-0">
                                    <div className="transform-1-0-0-1-0-1-0-0">
                                        <div className="transform-1-0-0-1-0-1-0-0-0">
                                            <div className="transform-text-2">Y</div>
                                        </div>
                                    </div>
                                    <div className="transform-rectangle_2-8">
                                        <div className="transform-1-0-0-1-0-1-0-1-0">
                                            <div className="transform-text-13">0</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="transform-rectangle_27-8">
                                <div className="transform-1-0-0-1-0-2-0">
                                    <div className="transform-1-0-0-1-0-2-0-0">
                                        <div className="transform-1-0-0-1-0-2-0-0-0">
                                            <div className="transform-text-139">Z</div>
                                        </div>
                                    </div>
                                    <div className="transform-rectangle_2-4">
                                        <div className="transform-1-0-0-1-0-2-0-1-0">
                                            <div className="transform-text-7">0</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="transform-2">
            <div className="transform-rectangle-17">
                <div className="transform-2-0-0">
                    <div className="transform-2-0-0-0">
                        <div className="transform-2-0-0-0-0">
                            <div className="transform-text-6">Rotation</div>
                        </div>
                    </div>
                    <div className="transform-rectangle_28-4">
                        <div className="transform-2-0-0-1-0">
                            <div className="transform-rectangle_27-7">
                                <div className="transform-2-0-0-1-0-0-0">
                                    <div className="transform-2-0-0-1-0-0-0-0">
                                        <div className="transform-2-0-0-1-0-0-0-0-0">
                                            <div className="transform-text-87">X</div>
                                        </div>
                                    </div>
                                    <div className="transform-rectangle_2-41">
                                        <div className="transform-2-0-0-1-0-0-0-1-0">
                                            <div className="transform-text-84">0</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="transform-rectangle_27-70">
                                <div className="transform-2-0-0-1-0-1-0">
                                    <div className="transform-2-0-0-1-0-1-0-0">
                                        <div className="transform-2-0-0-1-0-1-0-0-0">
                                            <div className="transform-text-40">Y</div>
                                        </div>
                                    </div>
                                    <div className="transform-rectangle_2-6">
                                        <div className="transform-2-0-0-1-0-1-0-1-0">
                                            <div className="transform-text-48">0</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="transform-rectangle_27-0">
                                <div className="transform-2-0-0-1-0-2-0">
                                    <div className="transform-2-0-0-1-0-2-0-0">
                                        <div className="transform-2-0-0-1-0-2-0-0-0">
                                            <div className="transform-text-5">Z</div>
                                        </div>
                                    </div>
                                    <div className="transform-rectangle_2-1">
                                        <div className="transform-2-0-0-1-0-2-0-1-0">
                                            <div className="transform-text-89">0</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="transform-3">
            <div className="transform-rectangle-9">
                <div className="transform-3-0-0">
                    <div className="transform-3-0-0-0">
                        <div className="transform-3-0-0-0-0">
                            <div className="transform-text-44">Scale</div>
                        </div>
                    </div>
                    <div className="transform-rectangle_28-43">
                        <div className="transform-3-0-0-1-0">
                            <div className="transform-rectangle_27-74">
                                <div className="transform-3-0-0-1-0-0-0">
                                    <div className="transform-3-0-0-1-0-0-0-0">
                                        <div className="transform-3-0-0-1-0-0-0-0-0">
                                            <div className="transform-text-16">X</div>
                                        </div>
                                    </div>
                                    <div className="transform-rectangle_2-0">
                                        <div className="transform-3-0-0-1-0-0-0-1-0">
                                            <div className="transform-text-50">1</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="transform-rectangle_27-5">
                                <div className="transform-3-0-0-1-0-1-0">
                                    <div className="transform-3-0-0-1-0-1-0-0">
                                        <div className="transform-3-0-0-1-0-1-0-0-0">
                                            <div className="transform-text-61">Y</div>
                                        </div>
                                    </div>
                                    <div className="transform-rectangle_2-42">
                                        <div className="transform-3-0-0-1-0-1-0-1-0">
                                            <div className="transform-text-56">1</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="transform-rectangle_27-19">
                                <div className="transform-3-0-0-1-0-2-0">
                                    <div className="transform-3-0-0-1-0-2-0-0">
                                        <div className="transform-3-0-0-1-0-2-0-0-0">
                                            <div className="transform-text-0">Z</div>
                                        </div>
                                    </div>
                                    <div className="transform-rectangle_2-3">
                                        <div className="transform-3-0-0-1-0-2-0-1-0">
                                            <div className="transform-text-33">1</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="transform-4">
            <div className="transform-line_2" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
