// Generated by https://pagedraw.io/pages/9927
import React from 'react';
import Gameobjectlist from './gameobjectlist';
import Scene from './scene';
import Inspector from './inspector';
import Fileexplorer from './fileexplorer';
import './zinterface.css';


function render() {
    return <div className="zinterface-zinterface-5">
        <div className="zinterface-0">
            <div className="zinterface-0-0">
                <div className="zinterface-0-0-0">
                    <div className="zinterface-gameobjectlist_instance-5">
                        <Gameobjectlist /> 
                    </div>
                </div>
            </div>
            <div className="zinterface-scene_instance-7">
                <Scene /> 
            </div>
            <div className="zinterface-inspector_instance-0">
                <Inspector /> 
            </div>
        </div>
        <div className="zinterface-1">
            <div className="zinterface-fileexplorer_instance-3">
                <Fileexplorer /> 
            </div>
        </div>
        <div className="zinterface-2" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
