// Generated by https://pagedraw.io/pages/9927
import React from 'react';
import './header.css';


function render() {
    return <div className="header-header-9">
        <div className="header-0">
            <img src="https://pagedraw-images.s3-us-west-1.amazonaws.com/1847039577646615-1525289018545-7FD531E2-CBD7-4211-B4A0-CF04A0EF544C.png" className="header-logo_icon-5" /> 
            <div className="header-0-1">
                <div className="header-0-1-0">
                    <div className="header-spaceplatforms-4">PythonEngine</div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
