// Generated by https://pagedraw.io/pages/9927
import React from 'react';
import './inspector.css';

function render() {
    return <div className="inspector-inspector-6">
        <div className="inspector-0">
            <div className="inspector-rectangle_4">
                <div className="inspector-0-0-0">
                    <div className="inspector-gameobjectlist-3">Inspector</div>
                </div>
            </div>
            <div className="inspector-rectangle_3" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}