// Generated by https://pagedraw.io/pages/9927
import Gameobjectlist from './gameobjectlist';
import Fileexplorer from './fileexplorer';
import Inspector from './inspector';
import React from 'react';
import './interface.css';

function render() {
    return <div className="interface-interface-5">
        <div className="interface-0">
            <div className="interface-0-0">
                <div className="interface-0-0-0">
                    <div className="interface-gameobjectlist_instance-5">
                        <Gameobjectlist /> 
                    </div>
                </div>
                <div className="interface-0-0-1">
                    <div className="interface-fileexplorer_instance-3">
                        <Fileexplorer /> 
                    </div>
                </div>
            </div>
            <div className="interface-inspector_instance-0">
                <Inspector /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}