// Generated by https://pagedraw.io/pages/9927
import React from 'react';
import './fileexplorer.css';


function render() {
    return <div className="fileexplorer-fileexplorer-6">
        <div className="fileexplorer-0">
            <div className="fileexplorer-rectangle_4">
                <div className="fileexplorer-0-0-0">
                    <div className="fileexplorer-gameobjectlist-6">
                        File Explorer
                    </div>
                </div>
            </div>
            <div className="fileexplorer-rectangle_3" /> 
        </div>
        <div className="fileexplorer-1">
            <div className="fileexplorer-rectangle-3">
                <div className="fileexplorer-1-0-0">
                    <div className="fileexplorer-rectangle_2">
                        <div className="fileexplorer-1-0-0-0-0">
                            <div className="fileexplorer-1-0-0-0-0-0">
                                <div className="fileexplorer-1-0-0-0-0-0-0">
                                    <div className="fileexplorer-line_3" /> 
                                </div>
                            </div>
                            <div className="fileexplorer-line_2" /> 
                            <div className="fileexplorer-1-0-0-0-0-2">
                                <div className="fileexplorer-1-0-0-0-0-2-0">
                                    <div className="fileexplorer-line_3-2" /> 
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="fileexplorer-rectangle_2-7">
                        <div className="fileexplorer-1-0-0-1-0">
                            <div className="fileexplorer-line_3-6" /> 
                            <div className="fileexplorer-line_3-9" /> 
                        </div>
                    </div>
                    <div className="fileexplorer-rectangle_2-8">
                        <div className="fileexplorer-1-0-0-2-0">
                            <div className="fileexplorer-text-2">Search...</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
